### ISSUE TITLE
Gtk issue

### ISSUE THREAD

**Issue by alex000090** [sailfishos-open/waydroid#21]
Dear developer,
I've installed waydroid for Sailfish feom Chum repo. After waydroid init I try to start waydroid and I catch error "Namespace Gtk not avaiable" from python. So waydroid can't start.

Sony Eperia 10 III
Sailfish X

**Comment by Dracks** [comment]
you should run it with waydroid-settings or waydroid-runner, the waydroid command start, I think is a generic function for PC not for sailfish.

**Comment by piggz** [comment]
There are many issues which can cause waydroid on sailfish not to start, but its unlikely to be Gtk, as thats not used anywhere.  Please provide logs from "waydroid log" and "waydroid logcat"

**Comment by olgabaranov** [comment]
Hi, 

not my issue, but I am having the same problem. Here is the log:
```  File "/opt/waydroid/tools/actions/initializer.py", line 205, in remote_init_client
    gi.require_version("Gtk", "3.0")
  File "/usr/lib64/python3.8/site-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gtk not available

(006555) [22:41:07] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(006555) [22:41:07] *** output passed to waydroid stdout, not to this log ***
(006560) [22:41:18] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(006560) [22:41:18] *** output passed to waydroid stdout, not to this log ***
(006570) [22:42:11] ERROR: Namespace Gtk not available
(006570) [22:42:11] See also: <https://github.com/waydroid>
(006570) [22:42:11] Traceback (most recent call last):
  File "/opt/waydroid/tools/__init__.py", line 113, in main
    actions.remote_init_client(args)
  File "/opt/waydroid/tools/actions/initializer.py", line 205, in remote_init_client
    gi.require_version("Gtk", "3.0")
  File "/usr/lib64/python3.8/site-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gtk not available

(006580) [22:43:04] ERROR: Namespace Gtk not available
(006580) [22:43:04] See also: <https://github.com/waydroid>
(006580) [22:43:04] Traceback (most recent call last):
  File "/opt/waydroid/tools/__init__.py", line 113, in main
    actions.remote_init_client(args)
  File "/opt/waydroid/tools/actions/initializer.py", line 205, in remote_init_client
    gi.require_version("Gtk", "3.0")
  File "/usr/lib64/python3.8/site-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gtk not available

(006583) [22:43:11] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(006583) [22:43:11] *** output passed to waydroid stdout, not to this log ***
(006598) [22:44:30] ERROR: Namespace Gtk not available
(006598) [22:44:30] See also: <https://github.com/waydroid>
(006598) [22:44:30] Traceback (most recent call last):
  File "/opt/waydroid/tools/__init__.py", line 113, in main
    actions.remote_init_client(args)
  File "/opt/waydroid/tools/actions/initializer.py", line 205, in remote_init_client
    gi.require_version("Gtk", "3.0")
  File "/usr/lib64/python3.8/site-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gtk not available

(006602) [22:44:35] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(006602) [22:44:35] *** output passed to waydroid stdout, not to this log ***
(006622) [22:46:08] ERROR: Namespace Gtk not available
(006622) [22:46:08] See also: <https://github.com/waydroid>
(006622) [22:46:08] Traceback (most recent call last):
  File "/opt/waydroid/tools/__init__.py", line 113, in main
    actions.remote_init_client(args)
  File "/opt/waydroid/tools/actions/initializer.py", line 205, in remote_init_client
    gi.require_version("Gtk", "3.0")
  File "/usr/lib64/python3.8/site-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gtk not available

(006625) [22:46:15] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(006625) [22:46:15] *** output passed to waydroid stdout, not to this log ***

```

and logcat 
`[22:47:23] WayDroid container is STOPPED
`

**Comment by mittorn** [comment]
>[20:00:49] Failed to add service waydroidhardware: -2147483647
>[20:00:49] Failed to add service waydroidhardware: -2147483647
change aidl2 to aidl3 in gbinder config
also enabling vibration service in hybris/hallium fixed boot for me
