### ISSUE TITLE
Xperia XZ2 fresh install not working

### ISSUE THREAD

**Issue by roundedrectangle** [sailfishos-open/waydroid#35]
Tried starting with waydroid-settings and waydroid-runner, had no success
When running `waydroid show-full-ui` it shows `WayDroid container is STOPPED`. And when running `waydroid container start` it shows "container failed to start". In the logs, however, it shows an error:

```
[waydroid-sensors-daemon] Failed to create SensorfwTemperatureSensor: Could not create sensorfw backend
(008431) [17:29:25] % mount -o remount,ro /var/lib/waydroid/images/vendor.img /var/lib/waydroid/rootfs/vendor
(008431) [17:29:25] % mount -o bind /vendor/lib/egl /var/lib/waydroid/rootfs/vendor/lib/egl
(008431) [17:29:25] % mount -o bind /vendor/lib64/egl /var/lib/waydroid/rootfs/vendor/lib64/egl
(008431) [17:29:25] % mount -o bind /odm /var/lib/waydroid/rootfs/odm_extra
(008431) [17:29:25] % mount -o bind /var/lib/waydroid/waydroid.prop /var/lib/waydroid/rootfs/vendor/waydroid.prop
(008431) [17:29:25] Save config: /var/lib/waydroid/waydroid.cfg
(008431) [17:29:25] % chmod 777 -R /dev/ashmem
(008431) [17:29:25] % chmod 777 -R /sys/kernel/debug/sync/sw_sync
(008431) [17:29:25] % chmod 777 -R /dev/dri
(008431) [17:29:25] % chmod 777 -R /dev/ion
(008431) [17:29:25] % chmod 777 -R /dev/video
(008431) [17:29:25] % chmod 777 -R /dev/video2
(008431) [17:29:25] % chmod 777 -R /dev/video1
(008431) [17:29:25] % chmod 777 -R /dev/video33
(008431) [17:29:25] % chmod 777 -R /dev/video32
(008431) [17:29:25] % chmod 777 -R /dev/video0
(008431) [17:29:25] % lxc-start -P /var/lib/waydroid/lxc -F -n waydroid -- /init
(008431) [17:29:25] New background process: pid=8538, output=background
lxc-start: waydroid: ../src/lxc/network.c: netdev_configure_server_veth: 711 No such file or directory - Failed to attach "vethJqubxz" to bridge "waydroid0", bridge interface doesn't exist
lxc-start: waydroid: ../src/lxc/network.c: lxc_create_network_priv: 3427 No such file or directory - Failed to create network device
lxc-start: waydroid: ../src/lxc/start.c: lxc_spawn: 1840 Failed to create the network
lxc-start: waydroid: ../src/lxc/start.c: __lxc_start: 2107 Failed to spawn container "waydroid"
lxc-start: waydroid: ../src/lxc/conf.c: run_buffer: 322 Script exited with status 126
lxc-start: waydroid: ../src/lxc/start.c: lxc_end: 985 Failed to run lxc.hook.post-stop for container "waydroid"
lxc-start: waydroid: ../src/lxc/tools/lxc_start.c: main: 306 The container failed to start
lxc-start: waydroid: ../src/lxc/tools/lxc_start.c: main: 311 Additional information can be obtained by setting the --logfile and --logpriority options
(008431) [17:29:25] waiting 10 seconds for container to start...
(008431) [17:29:26] waiting 9 seconds for container to start...
(008431) [17:29:27] waiting 8 seconds for container to start...
(008431) [17:29:28] waiting 7 seconds for container to start...
(008431) [17:29:29] waiting 6 seconds for container to start...
(008566) [17:29:30] UserMonitor service is not even started
(008566) [17:29:30] Clipboard service is not even started
(008431) [17:29:30] waiting 5 seconds for container to start...
(008386) [17:29:30] UserMonitor service is not even started
(008386) [17:29:30] Clipboard service is not even started
(008431) [17:29:31] waiting 4 seconds for container to start...
(008431) [17:29:32] waiting 3 seconds for container to start...
(008431) [17:29:33] waiting 2 seconds for container to start...
(008431) [17:29:34] waiting 1 seconds for container to start...
(008431) [17:29:35] ERROR: container failed to start
(008431) [17:29:35] See also: <https://github.com/waydroid>
(008431) [17:29:35] Traceback (most recent call last):
  File "/opt/waydroid/tools/__init__.py", line 68, in main
    actions.container_manager.start(args)
  File "/opt/waydroid/tools/actions/container_manager.py", line 131, in start
    raise OSError("container failed to start")
OSError: container failed to start
```

**Comment by roundedrectangle** [comment]
Fixed by [commenting a line in config](https://github.com/sailfishos-open/waydroid/issues/30) (not sure why it is not fixed) and [uncommenting a line in dnsmasq config](https://github.com/sailfishos-open/waydroid#dnsmasq-failed-to-create-listening-socket-for-1921682501-address-already-in-use).
